### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by kjohn01** [internlens-tw/InternLens#11]
實名制？匿名制？
參考：
[http://www.discourse.org/](url)

**Comment by lichin-lin** [comment]
目前我做匿名制 但是傾向於實名

**Comment by kjohn01** [comment]
目前留言的部分是做像是PTT 那種取ID的半匿名制，不知道大家覺得怎麼樣呢？
@linamy85 @MIBlue119

**Comment by lichin-lin** [comment]
匿名制 東西都存起來
