### ISSUE TITLE
log in check before submit response

### ISSUE THREAD

**Issue by kjohn01** [internlens-tw/InternLens#17]
要去google form填心得之前必須先確認有沒有登入，
如果還沒登入就導到登入頁面

**Comment by lichin-lin** [comment]
請問這是為什麼呢~~~~~
我雖然登入了 不過資訊只在我們的透視鏡網頁內有效
連到表單之後就是 google 那邊的事情了不是嗎~?

**Comment by kjohn01** [comment]
因為要確定留心得的人要先登入
跟留言的概念一樣，我們自己要能找到留心得的人是誰，這樣到時候有問題才找得到人～

不過這樣技術上好像的確沒辦法從我們網頁這邊影響到google那邊...
還是有什麼方法？

**Comment by lichin-lin** [comment]
完全沒有辦法 一離開我們這邊
google 的資訊我們真的拿不到
畢竟在我們這邊登入 完全在表單那邊沒有強制力

**Comment by kjohn01** [comment]
所以必須是之後不用google表單，變成直接從網站上留心得，然後存在自己server上才能這樣弄是嗎？

**Comment by MIBlue119** [comment]
lichin~ 那假如把表單的Embedded html 內嵌到我們的一頁中
這樣子是不是要求大家要先登入FB跟Ｇ＋ ，才到到有內嵌表單的那一頁了

**Comment by kjohn01** [comment]
但這樣我們還是沒辦法追蹤到哪個人發了哪一篇心得，因為在我們這登入，跟在google端發心得是完全隔開的，就算你的按鈕會先檢查我們這有沒有登入也是一樣。
我覺得要解決這個只有一個方法就是放棄googleˊ，直接從我們這留心得，對嗎？
@lichin-lin @MIBlue119 @linamy85

**Comment by MIBlue119** [comment]
喔喔～我那個提出方案是想先初步要求必須先登入還有防止有人沒登入能拿到填選連結這件事～
雖然這一版無法track，但主要是想有這個動作，加深大部份人看重的心理，當然那些惡意的我們還是無法防止。

**Comment by lichin-lin** [comment]
在手刻一個 form 好像不會太久 但是我沒什麼時間QQ
我只能做到這禮拜 我六日又有計畫 等於我剩下三四五~~
這三天我又想解決不同瀏覽器間的UI 不希望大跑版

**Comment by kjohn01** [comment]
個人覺得目前的問卷還是有require google login， 應該就是同樣的效果（如果沒有要track的話）
所以可以等後來的版本再加進去就好～

**Comment by lichin-lin** [comment]
這部分好像沒什麼要修改的了
