### ISSUE TITLE
warning pop up window before submit response

### ISSUE THREAD

**Issue by kjohn01** [internlens-tw/InternLens#18]
在最後送出文章前，有個彈出視窗做最後確認，
說即使匿名也是要負擔法律責任，不要亂講話，
有“確認”跟“返回”可以按

**Comment by lichin-lin** [comment]
我是在發文前做了一個 勾勾
需要登入使用者確認後才能送出回應

**Comment by kjohn01** [comment]
這邊說的發文不是留言喔！
是說去填問卷留實習心得～

**Comment by lichin-lin** [comment]
填問卷的心得目前適用 google 表單
我們該怎麼讓他確認~XD?

**Comment by kjohn01** [comment]
沒關係這個feature是nice to have的，第一版先上線再來想辦法

**Comment by lichin-lin** [comment]
實習心得問卷可以加入匿名負責的勾選細項
與透視鏡網頁無直接關係

**Comment by kjohn01** [comment]
這樣好嗎？因為好像事實上是有關係的不是嗎＾＾“
