### ISSUE TITLE
lazy bag page

### ISSUE THREAD

**Issue by kjohn01** [internlens-tw/InternLens#2]
把懶人包的內容放到網站上

**Comment by kjohn01** [comment]
懶人包的頁面可能可以像fb照片那樣一張張的，然後旁邊有圖說，還可以留言討論（optional）
![screen shot 2017-03-20 at 3 05 29 pm](https://cloud.githubusercontent.com/assets/8452056/24090875/eb4b2d18-0d7e-11e7-90a8-4f1b9c75e183.png)

**Comment by lichin-lin** [comment]
目前直接連到FB
