### ISSUE TITLE
Unable to go back from article page

### ISSUE THREAD

**Issue by kjohn01** [internlens-tw/InternLens#26]
從首頁點進文章後，案叉叉與上一頁都沒辦法返回
只能refresh

**Comment by lichin-lin** [comment]
這個 bug 已經修掉了
不過現在想要重新設計 url
所以點擊不會再跳出視窗而是換到另一頁

**Comment by kjohn01** [comment]
我覺得目前這樣跳出視窗還不錯呀？
想要換頁的原因是什麼呢？

**Comment by lichin-lin** [comment]
因為 url 需要編號
考慮到說大家會分享 link
如果目前都只在同一頁點擊是比較可惜的
例如
A公司 (.../post/1)
B公司 (.../post/2)

這樣在FB分享也才能直接連到那篇文章

**Comment by kjohn01** [comment]
OK!
