### ISSUE TITLE
如何登出阿？

### ISSUE THREAD

**Issue by kjohn01** [internlens-tw/InternLens#37]

**Comment by lichin-lin** [comment]
真的需要登出嗎XD 
目前是一個小時會踢掉一次

**Comment by kjohn01** [comment]
我不知道做登出的成本怎麼樣
如果很麻煩的話是沒有到一定必要啦～
但如果是舉手之勞的話我覺得做一下比較好
有些人會覺得沒有登出很像被綁架了～

到是一個小時踢掉一次感覺就不太好了，這樣變成我幾乎每次來都要重登？

**Comment by lichin-lin** [comment]
okok!!!
