### ISSUE TITLE
remove comment tags

### ISSUE THREAD

**Issue by kjohn01** [internlens-tw/InternLens#46]

**Comment by lichin-lin** [comment]
done

**Comment by kjohn01** [comment]
![default](https://cloud.githubusercontent.com/assets/8452056/24839197/a901bde0-1d88-11e7-9361-c639bf2b1d3a.png)

**Comment by kjohn01** [comment]
![2](https://cloud.githubusercontent.com/assets/8452056/24839246/5c99cfc8-1d89-11e7-8627-b9e6b01713d0.png)
