### ISSUE TITLE
fb login

### ISSUE THREAD

**Issue by kjohn01** [internlens-tw/InternLens#8]
至少要拿的資料：

- [ ] avatar

- [ ] username

- [ ] email

- [ ] work exp.

**Comment by kjohn01** [comment]
按了登入以後跳出一頁空白的什麼都沒發生耶？

**Comment by kjohn01** [comment]
可以順利登入的：

- [ ] chrome desktop

- [ ] chrome mobile

- [ ] firefox desktop

- [ ] firefox mobile

- [ ] safari desktop

- [ ] safari mobile

**Comment by lichin-lin** [comment]
目前應該只有 Message 上面會出事，其他的我都可以順利登入。
